if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")

    set(FLAG_ENABLE_ALL_WARNINGS -Wall -Wextra)
    set(FLAG_WARNINGS_AS_ERRORS -Werror)
    set(FLAG_ZERO_OPTIMIZATION -O0)
    set(FLAG_MAX_OPTIMIZATION -O2)

elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")

    set(FLAG_ENABLE_ALL_WARNINGS -Wall -Wextra)
    set(FLAG_WARNINGS_AS_ERRORS -Werror)
    set(FLAG_ZERO_OPTIMIZATION -O0)
    set(FLAG_MAX_OPTIMIZATION -O2)

elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")

    set(FLAG_ENABLE_ALL_WARNINGS /W4)
    set(FLAG_WARNINGS_AS_ERRORS /WX)
    set(FLAG_ZERO_OPTIMIZATION /Od)
    set(FLAG_MAX_OPTIMIZATION /O2)

endif()

set(BASE_FLAGS ${FLAG_ENABLE_ALL_WARNINGS} ${FLAG_WARNINGS_AS_ERRORS})
set(DEBUG_FLAGS ${BASE_FLAGS} ${FLAG_ZERO_OPTIMIZATION})
set(RELEASE_FLAGS ${BASE_FLAGS} ${FLAG_MAX_OPTIMIZATION})
