macro(assign_bool var)
     if(${ARGN})
         set(${var} ON)
     else()
         set(${var} OFF)
     endif()
endmacro()

function(cpm_add_library)
    set(options)
    set(oneValueArgs TARGET)
    set(multiValueArgs SOURCES TESTS)
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    add_library(${ARG_TARGET} ${ARG_SOURCES})
    target_include_directories(${ARG_TARGET} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})

    target_sources(unit_tests PRIVATE ${ARG_TESTS})
    target_link_libraries(unit_tests ${ARG_TARGET})
endfunction()
