name: analyze

on: workflow_call

jobs:

  clang-tidy:
    
    runs-on: ubuntu-24.04

    steps:

      - uses: actions/checkout@v4

      - name: Set VCPKG_ROOT
        shell: bash
        run: echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> "$GITHUB_ENV"

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y clang-tidy

      - name: Configure
        run: >
          cmake --preset linux-clang
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DCMAKE_CXX_CLANG_TIDY="clang-tidy"
      
      - name: Build
        run: cmake --build build/linux-clang --config Debug --parallel
