name: cicd

on: [ push, pull_request, workflow_dispatch ]

jobs:

    analyze:
        uses: ./.github/workflows/analyze.yml
        
    sanitize:
        uses: ./.github/workflows/sanitize.yml
    
    test:
        uses: ./.github/workflows/test.yml
