name: cicd

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - { name: arm64-apple-clang, runs_on: macos-15         }
          - { name: arm64-linux-clang, runs_on: ubuntu-24.04-arm }
          - { name: arm64-linux-gnu,   runs_on: ubuntu-24.04-arm }
          - { name: x64-apple-clang,   runs_on: macos-14         }
          - { name: x64-linux-clang,   runs_on: ubuntu-24.04     }
          - { name: x64-linux-gnu,     runs_on: ubuntu-24.04     }
          - { name: x64-windows-msvc,  runs_on: windows-2025     }
          - { name: x64-windows-clang, runs_on: windows-2025     }

    runs-on: ${{ matrix.runs_on }}
    env:
      VCPKG_ROOT: ${{ github.env.VCPKG_INSTALLATION_ROOT }}

    steps:
      - uses: actions/checkout@v4
      - name: Configure & build (${{ matrix.name }})
        run: |
          cmake --preset ${{ matrix.name }}
          cmake --build --preset ${{ matrix.name }}
          ctest --preset ${{ matrix.name }}
